#ifndef _Q4SSERVERSTATE_H_
#define _Q4SSERVERSTATE_H_

enum Q4SServerState
{   
    Q4SSERVERSTATE_INVALID,
    Q4SSERVERSTATE_INIT,
    Q4SSERVERSTATE_HANDSHAKE,
    Q4SSERVERSTATE_NEGOTIATION,
    Q4SSERVERSTATE_CONTINUITY,
    Q4SSERVERSTATE_TERMINATION,
};

#endif  // _Q4SSERVERSTATE_H_